language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm install
script:
  - yarn build # 构建
cache: yarn
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./.vuepress/dist
  github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  target_branch: master
  on:
    branch: docs #  发布的时候使用的branch